///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AppliedJobModelDataJobApplicationsCompany {
/*
{
  "company_id": 14,
  "logo": "https://assets.bossjob.com/companies/14/logo/Y05sPZehN4MiJBVWLoYiLkT40QhMIkEPofpR3TYY.jpeg",
  "name": "Philippine Dragon Media Network",
  "is_verify": false
} 
*/

  int? companyId;
  String? logo;
  String? name;
  bool? isVerify;

  AppliedJobModelDataJobApplicationsCompany({
    this.companyId,
    this.logo,
    this.name,
    this.isVerify,
  });
  AppliedJobModelDataJobApplicationsCompany.fromJson(
      Map<String, dynamic> json) {
    companyId = json["company_id"]?.toInt();
    logo = json["logo"]?.toString();
    name = json["name"]?.toString();
    isVerify = json["is_verify"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["company_id"] = companyId;
    data["logo"] = logo;
    data["name"] = name;
    data["is_verify"] = isVerify;
    return data;
  }
}

class AppliedJobModelDataJobApplicationsJob {
/*
{
  "job_id": 21726,
  "status_key": "active",
  "job_title": "Videographer / Graphic Designer",
  "job_location": "Manila",
  "degree": "Diploma",
  "job_type": "Full-time",
  "xp_lvl": "1 - 3 years",
  "salary_range_from": 15000,
  "salary_range_to": 25000,
  "job_skills": "Graphic Design,Photography"
} 
*/

  int? jobId;
  String? statusKey;
  String? jobTitle;
  String? jobLocation;
  String? degree;
  String? jobType;
  String? xpLvl;
  String? salaryRangeFrom;
  String? salaryRangeTo;
  String? jobSkills;

  AppliedJobModelDataJobApplicationsJob({
    this.jobId,
    this.statusKey,
    this.jobTitle,
    this.jobLocation,
    this.degree,
    this.jobType,
    this.xpLvl,
    this.salaryRangeFrom,
    this.salaryRangeTo,
    this.jobSkills,
  });
  AppliedJobModelDataJobApplicationsJob.fromJson(Map<String, dynamic> json) {
    jobId = json["job_id"]?.toInt();
    statusKey = json["status_key"]?.toString();
    jobTitle = json["job_title"]?.toString();
    jobLocation = json["job_location"]?.toString();
    degree = json["degree"]?.toString();
    jobType = json["job_type"]?.toString();
    xpLvl = json["xp_lvl"]?.toString();
    salaryRangeFrom = json["salary_range_from"]?.toString();
    salaryRangeTo = json["salary_range_to"]?.toString();
    jobSkills = json["job_skills"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["job_id"] = jobId;
    data["status_key"] = statusKey;
    data["job_title"] = jobTitle;
    data["job_location"] = jobLocation;
    data["degree"] = degree;
    data["job_type"] = jobType;
    data["xp_lvl"] = xpLvl;
    data["salary_range_from"] = salaryRangeFrom;
    data["salary_range_to"] = salaryRangeTo;
    data["job_skills"] = jobSkills;
    return data;
  }
}

class AppliedJobModelDataJobApplications {
/*
{
  "job_application_id": 4251712,
  "dialogue_id": 4252681,
  "status_id": 1,
  "status_value": "New",
  "created_at": "2021-09-20 11:14:09",
  "job": {
    "job_id": 21726,
    "status_key": "active",
    "job_title": "Videographer / Graphic Designer",
    "job_location": "Manila",
    "degree": "Diploma",
    "job_type": "Full-time",
    "xp_lvl": "1 - 3 years",
    "salary_range_from": 15000,
    "salary_range_to": 25000,
    "job_skills": "Graphic Design,Photography"
  },
  "company": {
    "company_id": 14,
    "logo": "https://assets.bossjob.com/companies/14/logo/Y05sPZehN4MiJBVWLoYiLkT40QhMIkEPofpR3TYY.jpeg",
    "name": "Philippine Dragon Media Network",
    "is_verify": false
  }
} 
*/

  int? jobApplicationId;
  int? dialogueId;
  int? statusId;
  String? statusValue;
  String? createdAt;
  AppliedJobModelDataJobApplicationsJob? job;
  AppliedJobModelDataJobApplicationsCompany? company;

  AppliedJobModelDataJobApplications({
    this.jobApplicationId,
    this.dialogueId,
    this.statusId,
    this.statusValue,
    this.createdAt,
    this.job,
    this.company,
  });
  AppliedJobModelDataJobApplications.fromJson(Map<String, dynamic> json) {
    jobApplicationId = json["job_application_id"]?.toInt();
    dialogueId = json["dialogue_id"]?.toInt();
    statusId = json["status_id"]?.toInt();
    statusValue = json["status_value"]?.toString();
    createdAt = json["created_at"]?.toString();
    job = (json["job"] != null)
        ? AppliedJobModelDataJobApplicationsJob.fromJson(json["job"])
        : null;
    company = (json["company"] != null)
        ? AppliedJobModelDataJobApplicationsCompany.fromJson(json["company"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["job_application_id"] = jobApplicationId;
    data["dialogue_id"] = dialogueId;
    data["status_id"] = statusId;
    data["status_value"] = statusValue;
    data["created_at"] = createdAt;
    if (job != null) {
      data["job"] = job!.toJson();
    }
    if (company != null) {
      data["company"] = company!.toJson();
    }
    return data;
  }
}

class AppliedJobModelData {
/*
{
  "page": "1",
  "total_num": 1,
  "total_pages": 1,
  "job_applications": [
    {
      "job_application_id": 4251712,
      "dialogue_id": 4252681,
      "status_id": 1,
      "status_value": "New",
      "created_at": "2021-09-20 11:14:09",
      "job": {
        "job_id": 21726,
        "status_key": "active",
        "job_title": "Videographer / Graphic Designer",
        "job_location": "Manila",
        "degree": "Diploma",
        "job_type": "Full-time",
        "xp_lvl": "1 - 3 years",
        "salary_range_from": 15000,
        "salary_range_to": 25000,
        "job_skills": "Graphic Design,Photography"
      },
      "company": {
        "company_id": 14,
        "logo": "https://assets.bossjob.com/companies/14/logo/Y05sPZehN4MiJBVWLoYiLkT40QhMIkEPofpR3TYY.jpeg",
        "name": "Philippine Dragon Media Network",
        "is_verify": false
      }
    }
  ]
} 
*/

  String? page;
  int? totalNum;
  int? totalPages;
  List<AppliedJobModelDataJobApplications?>? jobApplications;

  AppliedJobModelData({
    this.page,
    this.totalNum,
    this.totalPages,
    this.jobApplications,
  });
  AppliedJobModelData.fromJson(Map<String, dynamic> json) {
    page = json["page"]?.toString();
    totalNum = json["total_num"]?.toInt();
    totalPages = json["total_pages"]?.toInt();
    if (json["job_applications"] != null) {
      final v = json["job_applications"];
      final arr0 = <AppliedJobModelDataJobApplications>[];
      v.forEach((v) {
        arr0.add(AppliedJobModelDataJobApplications.fromJson(v));
      });
      jobApplications = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["page"] = page;
    data["total_num"] = totalNum;
    data["total_pages"] = totalPages;
    if (jobApplications != null) {
      final v = jobApplications;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["job_applications"] = arr0;
    }
    return data;
  }
}

class AppliedJobModel {
/*
{
  "message": "OK",
  "data": {
    "page": "1",
    "total_num": 1,
    "total_pages": 1,
    "job_applications": [
      {
        "job_application_id": 4251712,
        "dialogue_id": 4252681,
        "status_id": 1,
        "status_value": "New",
        "created_at": "2021-09-20 11:14:09",
        "job": {
          "job_id": 21726,
          "status_key": "active",
          "job_title": "Videographer / Graphic Designer",
          "job_location": "Manila",
          "degree": "Diploma",
          "job_type": "Full-time",
          "xp_lvl": "1 - 3 years",
          "salary_range_from": 15000,
          "salary_range_to": 25000,
          "job_skills": "Graphic Design,Photography"
        },
        "company": {
          "company_id": 14,
          "logo": "https://assets.bossjob.com/companies/14/logo/Y05sPZehN4MiJBVWLoYiLkT40QhMIkEPofpR3TYY.jpeg",
          "name": "Philippine Dragon Media Network",
          "is_verify": false
        }
      }
    ]
  },
  "status_code": 200
} 
*/

  String? message;
  AppliedJobModelData? data;
  int? statusCode;

  AppliedJobModel({
    this.message,
    this.data,
    this.statusCode,
  });
  AppliedJobModel.fromJson(Map<String, dynamic> json) {
    message = json["message"]?.toString();
    data = (json["data"] != null)
        ? AppliedJobModelData.fromJson(json["data"])
        : null;
    statusCode = json["status_code"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["message"] = message;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["status_code"] = statusCode;
    return data;
  }
}
