///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CompanyFilterModelDataCompanies {
/*
{
  "name": "R",
  "id": 21101
} 
*/

  String? name;
  int? id;

  CompanyFilterModelDataCompanies({
    this.name,
    this.id,
  });
  CompanyFilterModelDataCompanies.fromJson(Map<String, dynamic> json) {
    name = json["name"]?.toString();
    id = json["id"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["name"] = name;
    data["id"] = id;
    return data;
  }
}

class CompanyFilterModelData {
/*
{
  "max_score": 25.831932,
  "page": 1,
  "total_pages": 72,
  "size": 5,
  "total_num": 356,
  "query": "r",
  "params": "",
  "companies": [
    {
      "name": "R",
      "id": 21101
    }
  ]
} 
*/

  double? maxScore;
  int? page;
  int? totalPages;
  int? size;
  int? totalNum;
  String? query;
  String? params;
  List<CompanyFilterModelDataCompanies?>? companies;

  CompanyFilterModelData({
    this.maxScore,
    this.page,
    this.totalPages,
    this.size,
    this.totalNum,
    this.query,
    this.params,
    this.companies,
  });
  CompanyFilterModelData.fromJson(Map<String, dynamic> json) {
    maxScore = json["max_score"]?.toDouble();
    page = json["page"]?.toInt();
    totalPages = json["total_pages"]?.toInt();
    size = json["size"]?.toInt();
    totalNum = json["total_num"]?.toInt();
    query = json["query"]?.toString();
    params = json["params"]?.toString();
    if (json["companies"] != null) {
      final v = json["companies"];
      final arr0 = <CompanyFilterModelDataCompanies>[];
      v.forEach((v) {
        arr0.add(CompanyFilterModelDataCompanies.fromJson(v));
      });
      companies = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["max_score"] = maxScore;
    data["page"] = page;
    data["total_pages"] = totalPages;
    data["size"] = size;
    data["total_num"] = totalNum;
    data["query"] = query;
    data["params"] = params;
    if (companies != null) {
      final v = companies;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["companies"] = arr0;
    }
    return data;
  }
}

class CompanyFilterModel {
/*
{
  "message": "OK",
  "data": {
    "max_score": 25.831932,
    "page": 1,
    "total_pages": 72,
    "size": 5,
    "total_num": 356,
    "query": "r",
    "params": "",
    "companies": [
      {
        "name": "R",
        "id": 21101
      }
    ]
  },
  "status_code": 200
} 
*/

  String? message;
  CompanyFilterModelData? data;
  int? statusCode;

  CompanyFilterModel({
    this.message,
    this.data,
    this.statusCode,
  });
  CompanyFilterModel.fromJson(Map<String, dynamic> json) {
    message = json["message"]?.toString();
    data = (json["data"] != null)
        ? CompanyFilterModelData.fromJson(json["data"])
        : null;
    statusCode = json["status_code"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["message"] = message;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["status_code"] = statusCode;
    return data;
  }
}
