///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class IndustryFilterModelDataIndustry {
/*
{
  "id": 10,
  "value": "Information Technology",
  "key": "information_technology",
  "score": 3.9788015
} 
*/

  int? id;
  String? value;
  String? key;
  double? score;

  IndustryFilterModelDataIndustry({
    this.id,
    this.value,
    this.key,
    this.score,
  });
  IndustryFilterModelDataIndustry.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    value = json["value"]?.toString();
    key = json["key"]?.toString();
    score = json["score"]?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["value"] = value;
    data["key"] = key;
    data["score"] = score;
    return data;
  }
}

class IndustryFilterModelData {
/*
{
  "industry": [
    {
      "id": 10,
      "value": "Information Technology",
      "key": "information_technology",
      "score": 3.9788015
    }
  ],
  "max_score": 3.9788015,
  "page": 1,
  "total_pages": 1,
  "size": 10,
  "total_num": 1,
  "query": "tech"
} 
*/

  List<IndustryFilterModelDataIndustry?>? industry;
  double? maxScore;
  int? page;
  int? totalPages;
  int? size;
  int? totalNum;
  String? query;

  IndustryFilterModelData({
    this.industry,
    this.maxScore,
    this.page,
    this.totalPages,
    this.size,
    this.totalNum,
    this.query,
  });
  IndustryFilterModelData.fromJson(Map<String, dynamic> json) {
    if (json["industry"] != null) {
      final v = json["industry"];
      final arr0 = <IndustryFilterModelDataIndustry>[];
      v.forEach((v) {
        arr0.add(IndustryFilterModelDataIndustry.fromJson(v));
      });
      industry = arr0;
    }
    maxScore = json["max_score"]?.toDouble();
    page = json["page"]?.toInt();
    totalPages = json["total_pages"]?.toInt();
    size = json["size"]?.toInt();
    totalNum = json["total_num"]?.toInt();
    query = json["query"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (industry != null) {
      final v = industry;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["industry"] = arr0;
    }
    data["max_score"] = maxScore;
    data["page"] = page;
    data["total_pages"] = totalPages;
    data["size"] = size;
    data["total_num"] = totalNum;
    data["query"] = query;
    return data;
  }
}

class IndustryFilterModel {
/*
{
  "message": "OK",
  "data": {
    "industry": [
      {
        "id": 10,
        "value": "Information Technology",
        "key": "information_technology",
        "score": 3.9788015
      }
    ],
    "max_score": 3.9788015,
    "page": 1,
    "total_pages": 1,
    "size": 10,
    "total_num": 1,
    "query": "tech"
  },
  "status_code": 200
} 
*/

  String? message;
  IndustryFilterModelData? data;
  int? statusCode;

  IndustryFilterModel({
    this.message,
    this.data,
    this.statusCode,
  });
  IndustryFilterModel.fromJson(Map<String, dynamic> json) {
    message = json["message"]?.toString();
    data = (json["data"] != null)
        ? IndustryFilterModelData.fromJson(json["data"])
        : null;
    statusCode = json["status_code"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["message"] = message;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["status_code"] = statusCode;
    return data;
  }
}
