///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class JobTitleFilterModelDataJobs {
/*
{
  "name": "Junior Engineer",
  "id": 1223,
  "score": 23.80615
} 
*/

  String? name;
  int? id;
  double? score;

  JobTitleFilterModelDataJobs({
    this.name,
    this.id,
    this.score,
  });
  JobTitleFilterModelDataJobs.fromJson(Map<String, dynamic> json) {
    name = json["name"]?.toString();
    id = json["id"]?.toInt();
    score = json["score"]?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["name"] = name;
    data["id"] = id;
    data["score"] = score;
    return data;
  }
}

class JobTitleFilterModelData {
/*
{
  "jobs": [
    {
      "name": "Junior Engineer",
      "id": 1223,
      "score": 23.80615
    }
  ],
  "max_score": 23.80615,
  "page": 1,
  "total_pages": 12,
  "size": 5,
  "total_num": 57,
  "query": "junior"
} 
*/

  List<JobTitleFilterModelDataJobs?>? jobs;
  double? maxScore;
  int? page;
  int? totalPages;
  int? size;
  int? totalNum;
  String? query;

  JobTitleFilterModelData({
    this.jobs,
    this.maxScore,
    this.page,
    this.totalPages,
    this.size,
    this.totalNum,
    this.query,
  });
  JobTitleFilterModelData.fromJson(Map<String, dynamic> json) {
    if (json["jobs"] != null) {
      final v = json["jobs"];
      final arr0 = <JobTitleFilterModelDataJobs>[];
      v.forEach((v) {
        arr0.add(JobTitleFilterModelDataJobs.fromJson(v));
      });
      jobs = arr0;
    }
    maxScore = json["max_score"]?.toDouble();
    page = json["page"]?.toInt();
    totalPages = json["total_pages"]?.toInt();
    size = json["size"]?.toInt();
    totalNum = json["total_num"]?.toInt();
    query = json["query"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (jobs != null) {
      final v = jobs;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["jobs"] = arr0;
    }
    data["max_score"] = maxScore;
    data["page"] = page;
    data["total_pages"] = totalPages;
    data["size"] = size;
    data["total_num"] = totalNum;
    data["query"] = query;
    return data;
  }
}

class JobTitleFilterModel {
/*
{
  "message": "OK",
  "data": {
    "jobs": [
      {
        "name": "Junior Engineer",
        "id": 1223,
        "score": 23.80615
      }
    ],
    "max_score": 23.80615,
    "page": 1,
    "total_pages": 12,
    "size": 5,
    "total_num": 57,
    "query": "junior"
  },
  "status_code": 200
} 
*/

  String? message;
  JobTitleFilterModelData? data;
  int? statusCode;

  JobTitleFilterModel({
    this.message,
    this.data,
    this.statusCode,
  });
  JobTitleFilterModel.fromJson(Map<String, dynamic> json) {
    message = json["message"]?.toString();
    data = (json["data"] != null)
        ? JobTitleFilterModelData.fromJson(json["data"])
        : null;
    statusCode = json["status_code"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["message"] = message;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["status_code"] = statusCode;
    return data;
  }
}
