///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LocationModelDataLocations {
/*
{
  "id": 5,
  "value": "Alaminos",
  "key": "alaminos",
  "score": 1
} 
*/

  int? id;
  String? value;
  String? key;
  int? score;

  LocationModelDataLocations({
    this.id,
    this.value,
    this.key,
    this.score,
  });
  LocationModelDataLocations.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    value = json["value"]?.toString();
    key = json["key"]?.toString();
    score = json["score"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["value"] = value;
    data["key"] = key;
    data["score"] = score;
    return data;
  }
}

class LocationModelData {
/*
{
  "locations": [
    {
      "id": 5,
      "value": "Alaminos",
      "key": "alaminos",
      "score": 1
    }
  ],
  "max_score": null,
  "page": 1,
  "total_pages": 1,
  "size": 999,
  "total_num": 155,
  "query": null
} 
*/

  List<LocationModelDataLocations?>? locations;
  String? maxScore;
  int? page;
  int? totalPages;
  int? size;
  int? totalNum;
  String? query;

  LocationModelData({
    this.locations,
    this.maxScore,
    this.page,
    this.totalPages,
    this.size,
    this.totalNum,
    this.query,
  });
  LocationModelData.fromJson(Map<String, dynamic> json) {
    if (json["locations"] != null) {
      final v = json["locations"];
      final arr0 = <LocationModelDataLocations>[];
      v.forEach((v) {
        arr0.add(LocationModelDataLocations.fromJson(v));
      });
      locations = arr0;
    }
    maxScore = json["max_score"]?.toString();
    page = json["page"]?.toInt();
    totalPages = json["total_pages"]?.toInt();
    size = json["size"]?.toInt();
    totalNum = json["total_num"]?.toInt();
    query = json["query"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (locations != null) {
      final v = locations;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["locations"] = arr0;
    }
    data["max_score"] = maxScore;
    data["page"] = page;
    data["total_pages"] = totalPages;
    data["size"] = size;
    data["total_num"] = totalNum;
    data["query"] = query;
    return data;
  }
}

class LocationModel {
/*
{
  "message": "OK",
  "data": {
    "locations": [
      {
        "id": 5,
        "value": "Alaminos",
        "key": "alaminos",
        "score": 1
      }
    ],
    "max_score": null,
    "page": 1,
    "total_pages": 1,
    "size": 999,
    "total_num": 155,
    "query": null
  },
  "status_code": 200
} 
*/

  String? message;
  LocationModelData? data;
  int? statusCode;

  LocationModel({
    this.message,
    this.data,
    this.statusCode,
  });
  LocationModel.fromJson(Map<String, dynamic> json) {
    message = json["message"]?.toString();
    data = (json["data"] != null)
        ? LocationModelData.fromJson(json["data"])
        : null;
    statusCode = json["status_code"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["message"] = message;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["status_code"] = statusCode;
    return data;
  }
}
