///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginModelDataAuthentication {
/*
{
  "token_type": "Bearer",
  "expires_in": 86400,
  "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZGE2NmI5MDcxODhiMDlkNmIzMjBlMzM3M2RhZWJiZGQyNmIzZWM2OTNmZTU2NjFkNmUxNWZkZGE2ZmQzYTE4YjNlNjQ3M2VmNTgxMWExMTAiLCJpYXQiOjE2MzA1NTcyNDEsIm5iZiI6MTYzMDU1NzI0MSwiZXhwIjoxNjMwNjQzNjQxLCJzdWIiOiIyMjcxODA2Iiwic2NvcGVzIjpbXX0.BqcDQbsO10KHtMwusqXrMtho-lujlmt2-PtT09OzpabXToXpTZWV-tlIbYYIFqkO3w2DFEes4vk-vyeOtROyXZuxFtufI0zuJR1jvd0tUCPEeqDYEe_xW4DPR2hx3FM4crshQdxm8eaOqpACxnVbpZLJX78PTR7zPAfBjXVX3CazR7lwHMhMjE-i_MFK7FyI92qgO6M9bGd7FuRqY_cgQZAVobAYNE0UEjEPqDVjF2jiN6Gq1oSlWE7lDj0lHRkR0EeFjYgrKzdfreqJSXtTB2Ws8l0J2xDovqphIHs9FMiWioqbY-gS6PhcENzb04vfLmrBv2dmgMtpOZZM-dAYa_4J5nyeYUhOf33yaovXYc4UBZgpXWZBQMKVo3nkMTNKq_vdPaU7horS_tF_dHoc7aXSZKqCsBh-RkkaqxqUBjK-zZc3aMmpVfNZ3itHYIQUM6FEpiU5HA3tmlrPeC2onwtJwdrvqtzugG3vRnRFmRhqKK18NEyIg02Y3YCDp2qZvU-JaUqviDnEBGcMCfpMYzPfui5NOFLfWiNCUbVsAJZkDQbyd66eJeLDctrDHyNAsljKEJ4fyMT-f8oaaBGHEmcrtonANb9EkIdJJMtXjFx9w8nXFnG-eo7jcuqSX7RN9aZHV3f66mr-H6mK2EdN_vg2-iLfniMHcnCqL4zSXEk",
  "refresh_token": "def502007d57e00ca70e765b321a1feeeef7a1415241f38cf10c7b210e31f3d807aa9102282d0f2f2b39430c685249d33d2eb4cd215c8cca729e40a2c89b29373fe1a1f75ddc4f8f076e8fe622467202e0a300a24a0d33cfe7c572a7fd429d008239bfcd09d26498369db6f5adeafef8e4c63f8021a53914d45b0c22e92ae4a8a5524cb7e762cc6cec6b8507835666a3bdd6a44f98dbd61101639ed868f4710dfd70810cebbf004a8154672589f9fac1f9da5b29459ff95bdfdf9acf6eb0543e406484f3fac70aabd509996a723aee64c054e782c6a24549d79470f871c533b921fbb603c6b2b3df9652555654305cb7431c572917fce40e39bf4ce5f2ceda6debb6896c018931cdd88fc4334e5c95e8fa0532ad4bb69491ff594522520f5f46de2b03ac1718cd7aba504abfed040b56d31d75a68bbec286abadc926aac16b37d1ac64806866c952685dae0f66c1e640e958c7050b883a855b4c4d9ea8dee5f02fd653dfa96b88",
  "expired_at": "2021-09-03 04:34:01"
} 
*/

  String? tokenType;
  int? expiresIn;
  String? accessToken;
  String? refreshToken;
  String? expiredAt;

  LoginModelDataAuthentication({
    this.tokenType,
    this.expiresIn,
    this.accessToken,
    this.refreshToken,
    this.expiredAt,
  });
  LoginModelDataAuthentication.fromJson(Map<String, dynamic> json) {
    tokenType = json["token_type"]?.toString();
    expiresIn = json["expires_in"]?.toInt();
    accessToken = json["access_token"]?.toString();
    refreshToken = json["refresh_token"]?.toString();
    expiredAt = json["expired_at"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["token_type"] = tokenType;
    data["expires_in"] = expiresIn;
    data["access_token"] = accessToken;
    data["refresh_token"] = refreshToken;
    data["expired_at"] = expiredAt;
    return data;
  }
}

class LoginModelData {
/*
{
  "id": 2271806,
  "first_name": "Kelvin",
  "last_name": "Tam",
  "email": "kelvin@poseitech.com",
  "phone_num": "121312122",
  "avatar": null,
  "is_email_verify": false,
  "is_mobile_verified": false,
  "status_key": "active",
  "notice_period_id": 1,
  "is_profile_completed": true,
  "active_key": 1,
  "is_profile_update_required": false,
  "ats_user_id": null,
  "recruiter_latest_work_xp": null,
  "authentication": {
    "token_type": "Bearer",
    "expires_in": 86400,
    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZGE2NmI5MDcxODhiMDlkNmIzMjBlMzM3M2RhZWJiZGQyNmIzZWM2OTNmZTU2NjFkNmUxNWZkZGE2ZmQzYTE4YjNlNjQ3M2VmNTgxMWExMTAiLCJpYXQiOjE2MzA1NTcyNDEsIm5iZiI6MTYzMDU1NzI0MSwiZXhwIjoxNjMwNjQzNjQxLCJzdWIiOiIyMjcxODA2Iiwic2NvcGVzIjpbXX0.BqcDQbsO10KHtMwusqXrMtho-lujlmt2-PtT09OzpabXToXpTZWV-tlIbYYIFqkO3w2DFEes4vk-vyeOtROyXZuxFtufI0zuJR1jvd0tUCPEeqDYEe_xW4DPR2hx3FM4crshQdxm8eaOqpACxnVbpZLJX78PTR7zPAfBjXVX3CazR7lwHMhMjE-i_MFK7FyI92qgO6M9bGd7FuRqY_cgQZAVobAYNE0UEjEPqDVjF2jiN6Gq1oSlWE7lDj0lHRkR0EeFjYgrKzdfreqJSXtTB2Ws8l0J2xDovqphIHs9FMiWioqbY-gS6PhcENzb04vfLmrBv2dmgMtpOZZM-dAYa_4J5nyeYUhOf33yaovXYc4UBZgpXWZBQMKVo3nkMTNKq_vdPaU7horS_tF_dHoc7aXSZKqCsBh-RkkaqxqUBjK-zZc3aMmpVfNZ3itHYIQUM6FEpiU5HA3tmlrPeC2onwtJwdrvqtzugG3vRnRFmRhqKK18NEyIg02Y3YCDp2qZvU-JaUqviDnEBGcMCfpMYzPfui5NOFLfWiNCUbVsAJZkDQbyd66eJeLDctrDHyNAsljKEJ4fyMT-f8oaaBGHEmcrtonANb9EkIdJJMtXjFx9w8nXFnG-eo7jcuqSX7RN9aZHV3f66mr-H6mK2EdN_vg2-iLfniMHcnCqL4zSXEk",
    "refresh_token": "def502007d57e00ca70e765b321a1feeeef7a1415241f38cf10c7b210e31f3d807aa9102282d0f2f2b39430c685249d33d2eb4cd215c8cca729e40a2c89b29373fe1a1f75ddc4f8f076e8fe622467202e0a300a24a0d33cfe7c572a7fd429d008239bfcd09d26498369db6f5adeafef8e4c63f8021a53914d45b0c22e92ae4a8a5524cb7e762cc6cec6b8507835666a3bdd6a44f98dbd61101639ed868f4710dfd70810cebbf004a8154672589f9fac1f9da5b29459ff95bdfdf9acf6eb0543e406484f3fac70aabd509996a723aee64c054e782c6a24549d79470f871c533b921fbb603c6b2b3df9652555654305cb7431c572917fce40e39bf4ce5f2ceda6debb6896c018931cdd88fc4334e5c95e8fa0532ad4bb69491ff594522520f5f46de2b03ac1718cd7aba504abfed040b56d31d75a68bbec286abadc926aac16b37d1ac64806866c952685dae0f66c1e640e958c7050b883a855b4c4d9ea8dee5f02fd653dfa96b88",
    "expired_at": "2021-09-03 04:34:01"
  }
} 
*/

  int? id;
  String? firstName;
  String? lastName;
  String? email;
  String? phoneNum;
  String? avatar;
  bool? isEmailVerify;
  bool? isMobileVerified;
  String? statusKey;
  int? noticePeriodId;
  bool? isProfileCompleted;
  int? activeKey;
  bool? isProfileUpdateRequired;
  String? atsUserId;
  String? recruiterLatestWorkXp;
  LoginModelDataAuthentication? authentication;

  LoginModelData({
    this.id,
    this.firstName,
    this.lastName,
    this.email,
    this.phoneNum,
    this.avatar,
    this.isEmailVerify,
    this.isMobileVerified,
    this.statusKey,
    this.noticePeriodId,
    this.isProfileCompleted,
    this.activeKey,
    this.isProfileUpdateRequired,
    this.atsUserId,
    this.recruiterLatestWorkXp,
    this.authentication,
  });
  LoginModelData.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    firstName = json["first_name"]?.toString();
    lastName = json["last_name"]?.toString();
    email = json["email"]?.toString();
    phoneNum = json["phone_num"]?.toString();
    avatar = json["avatar"]?.toString();
    isEmailVerify = json["is_email_verify"];
    isMobileVerified = json["is_mobile_verified"];
    statusKey = json["status_key"]?.toString();
    noticePeriodId = json["notice_period_id"]?.toInt();
    isProfileCompleted = json["is_profile_completed"];
    activeKey = json["active_key"]?.toInt();
    isProfileUpdateRequired = json["is_profile_update_required"];
    atsUserId = json["ats_user_id"]?.toString();
    recruiterLatestWorkXp = json["recruiter_latest_work_xp"]?.toString();
    authentication = (json["authentication"] != null)
        ? LoginModelDataAuthentication.fromJson(json["authentication"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["first_name"] = firstName;
    data["last_name"] = lastName;
    data["email"] = email;
    data["phone_num"] = phoneNum;
    data["avatar"] = avatar;
    data["is_email_verify"] = isEmailVerify;
    data["is_mobile_verified"] = isMobileVerified;
    data["status_key"] = statusKey;
    data["notice_period_id"] = noticePeriodId;
    data["is_profile_completed"] = isProfileCompleted;
    data["active_key"] = activeKey;
    data["is_profile_update_required"] = isProfileUpdateRequired;
    data["ats_user_id"] = atsUserId;
    data["recruiter_latest_work_xp"] = recruiterLatestWorkXp;
    if (authentication != null) {
      data["authentication"] = authentication!.toJson();
    }
    return data;
  }
}

class LoginModel {
/*
{
  "success": true,
  "data": {
    "id": 2271806,
    "first_name": "Kelvin",
    "last_name": "Tam",
    "email": "kelvin@poseitech.com",
    "phone_num": "121312122",
    "avatar": null,
    "is_email_verify": false,
    "is_mobile_verified": false,
    "status_key": "active",
    "notice_period_id": 1,
    "is_profile_completed": true,
    "active_key": 1,
    "is_profile_update_required": false,
    "ats_user_id": null,
    "recruiter_latest_work_xp": null,
    "authentication": {
      "token_type": "Bearer",
      "expires_in": 86400,
      "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZGE2NmI5MDcxODhiMDlkNmIzMjBlMzM3M2RhZWJiZGQyNmIzZWM2OTNmZTU2NjFkNmUxNWZkZGE2ZmQzYTE4YjNlNjQ3M2VmNTgxMWExMTAiLCJpYXQiOjE2MzA1NTcyNDEsIm5iZiI6MTYzMDU1NzI0MSwiZXhwIjoxNjMwNjQzNjQxLCJzdWIiOiIyMjcxODA2Iiwic2NvcGVzIjpbXX0.BqcDQbsO10KHtMwusqXrMtho-lujlmt2-PtT09OzpabXToXpTZWV-tlIbYYIFqkO3w2DFEes4vk-vyeOtROyXZuxFtufI0zuJR1jvd0tUCPEeqDYEe_xW4DPR2hx3FM4crshQdxm8eaOqpACxnVbpZLJX78PTR7zPAfBjXVX3CazR7lwHMhMjE-i_MFK7FyI92qgO6M9bGd7FuRqY_cgQZAVobAYNE0UEjEPqDVjF2jiN6Gq1oSlWE7lDj0lHRkR0EeFjYgrKzdfreqJSXtTB2Ws8l0J2xDovqphIHs9FMiWioqbY-gS6PhcENzb04vfLmrBv2dmgMtpOZZM-dAYa_4J5nyeYUhOf33yaovXYc4UBZgpXWZBQMKVo3nkMTNKq_vdPaU7horS_tF_dHoc7aXSZKqCsBh-RkkaqxqUBjK-zZc3aMmpVfNZ3itHYIQUM6FEpiU5HA3tmlrPeC2onwtJwdrvqtzugG3vRnRFmRhqKK18NEyIg02Y3YCDp2qZvU-JaUqviDnEBGcMCfpMYzPfui5NOFLfWiNCUbVsAJZkDQbyd66eJeLDctrDHyNAsljKEJ4fyMT-f8oaaBGHEmcrtonANb9EkIdJJMtXjFx9w8nXFnG-eo7jcuqSX7RN9aZHV3f66mr-H6mK2EdN_vg2-iLfniMHcnCqL4zSXEk",
      "refresh_token": "def502007d57e00ca70e765b321a1feeeef7a1415241f38cf10c7b210e31f3d807aa9102282d0f2f2b39430c685249d33d2eb4cd215c8cca729e40a2c89b29373fe1a1f75ddc4f8f076e8fe622467202e0a300a24a0d33cfe7c572a7fd429d008239bfcd09d26498369db6f5adeafef8e4c63f8021a53914d45b0c22e92ae4a8a5524cb7e762cc6cec6b8507835666a3bdd6a44f98dbd61101639ed868f4710dfd70810cebbf004a8154672589f9fac1f9da5b29459ff95bdfdf9acf6eb0543e406484f3fac70aabd509996a723aee64c054e782c6a24549d79470f871c533b921fbb603c6b2b3df9652555654305cb7431c572917fce40e39bf4ce5f2ceda6debb6896c018931cdd88fc4334e5c95e8fa0532ad4bb69491ff594522520f5f46de2b03ac1718cd7aba504abfed040b56d31d75a68bbec286abadc926aac16b37d1ac64806866c952685dae0f66c1e640e958c7050b883a855b4c4d9ea8dee5f02fd653dfa96b88",
      "expired_at": "2021-09-03 04:34:01"
    }
  }
} 
*/

  bool? success;
  LoginModelData? data;

  LoginModel({
    this.success,
    this.data,
  });
  LoginModel.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data =
        (json["data"] != null) ? LoginModelData.fromJson(json["data"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    return data;
  }
}
