///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SchoolFilterModelDataSchools {
/*
{
  "name": "West Negros University",
  "id": 179,
  "score": 7.3952317
} 
*/

  String? name;
  int? id;
  double? score;

  SchoolFilterModelDataSchools({
    this.name,
    this.id,
    this.score,
  });
  SchoolFilterModelDataSchools.fromJson(Map<String, dynamic> json) {
    name = json["name"]?.toString();
    id = json["id"]?.toInt();
    score = json["score"]?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["name"] = name;
    data["id"] = id;
    data["score"] = score;
    return data;
  }
}

class SchoolFilterModelData {
/*
{
  "schools": [
    {
      "name": "West Negros University",
      "id": 179,
      "score": 7.3952317
    }
  ],
  "max_score": 7.3952317,
  "page": 1,
  "total_pages": 2,
  "size": 5,
  "total_num": 7,
  "query": "we"
} 
*/

  List<SchoolFilterModelDataSchools?>? schools;
  double? maxScore;
  int? page;
  int? totalPages;
  int? size;
  int? totalNum;
  String? query;

  SchoolFilterModelData({
    this.schools,
    this.maxScore,
    this.page,
    this.totalPages,
    this.size,
    this.totalNum,
    this.query,
  });
  SchoolFilterModelData.fromJson(Map<String, dynamic> json) {
    if (json["schools"] != null) {
      final v = json["schools"];
      final arr0 = <SchoolFilterModelDataSchools>[];
      v.forEach((v) {
        arr0.add(SchoolFilterModelDataSchools.fromJson(v));
      });
      schools = arr0;
    }
    maxScore = json["max_score"]?.toDouble();
    page = json["page"]?.toInt();
    totalPages = json["total_pages"]?.toInt();
    size = json["size"]?.toInt();
    totalNum = json["total_num"]?.toInt();
    query = json["query"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (schools != null) {
      final v = schools;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["schools"] = arr0;
    }
    data["max_score"] = maxScore;
    data["page"] = page;
    data["total_pages"] = totalPages;
    data["size"] = size;
    data["total_num"] = totalNum;
    data["query"] = query;
    return data;
  }
}

class SchoolFilterModel {
/*
{
  "message": "OK",
  "data": {
    "schools": [
      {
        "name": "West Negros University",
        "id": 179,
        "score": 7.3952317
      }
    ],
    "max_score": 7.3952317,
    "page": 1,
    "total_pages": 2,
    "size": 5,
    "total_num": 7,
    "query": "we"
  },
  "status_code": 200
} 
*/

  String? message;
  SchoolFilterModelData? data;
  int? statusCode;

  SchoolFilterModel({
    this.message,
    this.data,
    this.statusCode,
  });
  SchoolFilterModel.fromJson(Map<String, dynamic> json) {
    message = json["message"]?.toString();
    data = (json["data"] != null)
        ? SchoolFilterModelData.fromJson(json["data"])
        : null;
    statusCode = json["status_code"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["message"] = message;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["status_code"] = statusCode;
    return data;
  }
}
