///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SkillFilterModelDataSchools {
/*
{
  "id": 108,
  "value": "Internet",
  "key": "internet",
  "score": 5.660765
} 
*/

  int? id;
  String? value;
  String? key;
  double? score;

  SkillFilterModelDataSchools({
    this.id,
    this.value,
    this.key,
    this.score,
  });
  SkillFilterModelDataSchools.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    value = json["value"]?.toString();
    key = json["key"]?.toString();
    score = json["score"]?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["value"] = value;
    data["key"] = key;
    data["score"] = score;
    return data;
  }
}

class SkillFilterModelData {
/*
{
  "schools": [
    {
      "id": 108,
      "value": "Internet",
      "key": "internet",
      "score": 5.660765
    }
  ],
  "max_score": 5.660765,
  "page": 1,
  "total_pages": 5,
  "size": 5,
  "total_num": 22,
  "query": "in"
} 
*/

  List<SkillFilterModelDataSchools?>? schools;
  double? maxScore;
  int? page;
  int? totalPages;
  int? size;
  int? totalNum;
  String? query;

  SkillFilterModelData({
    this.schools,
    this.maxScore,
    this.page,
    this.totalPages,
    this.size,
    this.totalNum,
    this.query,
  });
  SkillFilterModelData.fromJson(Map<String, dynamic> json) {
    if (json["schools"] != null) {
      final v = json["schools"];
      final arr0 = <SkillFilterModelDataSchools>[];
      v.forEach((v) {
        arr0.add(SkillFilterModelDataSchools.fromJson(v));
      });
      schools = arr0;
    }
    maxScore = json["max_score"]?.toDouble();
    page = json["page"]?.toInt();
    totalPages = json["total_pages"]?.toInt();
    size = json["size"]?.toInt();
    totalNum = json["total_num"]?.toInt();
    query = json["query"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (schools != null) {
      final v = schools;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["schools"] = arr0;
    }
    data["max_score"] = maxScore;
    data["page"] = page;
    data["total_pages"] = totalPages;
    data["size"] = size;
    data["total_num"] = totalNum;
    data["query"] = query;
    return data;
  }
}

class SkillFilterModel {
/*
{
  "message": "OK",
  "data": {
    "schools": [
      {
        "id": 108,
        "value": "Internet",
        "key": "internet",
        "score": 5.660765
      }
    ],
    "max_score": 5.660765,
    "page": 1,
    "total_pages": 5,
    "size": 5,
    "total_num": 22,
    "query": "in"
  },
  "status_code": 200
} 
*/

  String? message;
  SkillFilterModelData? data;
  int? statusCode;

  SkillFilterModel({
    this.message,
    this.data,
    this.statusCode,
  });
  SkillFilterModel.fromJson(Map<String, dynamic> json) {
    message = json["message"]?.toString();
    data = (json["data"] != null)
        ? SkillFilterModelData.fromJson(json["data"])
        : null;
    statusCode = json["status_code"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["message"] = message;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["status_code"] = statusCode;
    return data;
  }
}
