///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserProfileModelDataSkills {
/*
{
  "id": 406225,
  "user_id": 2285293,
  "job_skills": "",
  "created_at": "2021-09-10T01:53:33.000000Z",
  "updated_at": "2021-09-10T01:53:33.000000Z"
} 
*/

  int? id;
  int? userId;
  String? jobSkills;
  String? createdAt;
  String? updatedAt;

  UserProfileModelDataSkills({
    this.id,
    this.userId,
    this.jobSkills,
    this.createdAt,
    this.updatedAt,
  });
  UserProfileModelDataSkills.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    userId = json["user_id"]?.toInt();
    jobSkills = json["job_skills"]?.toString();
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["user_id"] = userId;
    data["job_skills"] = jobSkills;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    return data;
  }
}

class UserProfileModelDataEducations {
/*
{
  "id": 2661629,
  "user_id": 2285293,
  "school_id": 167,
  "school": "Western Institute of Technology",
  "degree_key": "doctor",
  "field_of_study": "qwwqwqwwwww",
  "study_period_from": "2021-01-01",
  "study_period_to": "2021-03-01",
  "grade": "",
  "description": "",
  "location_key": "manila",
  "country_key": "ph",
  "status_key": "active",
  "is_currently_studying": 0,
  "created_at": "2021-09-03T06:11:11.000000Z",
  "updated_at": "2021-09-14T09:48:49.000000Z",
  "degree": "Doctor",
  "location": "Manila",
  "country": "Philippines"
} 
*/

  int? id;
  int? userId;
  int? schoolId;
  String? school;
  String? degreeKey;
  String? fieldOfStudy;
  String? studyPeriodFrom;
  String? studyPeriodTo;
  String? grade;
  String? description;
  String? locationKey;
  String? countryKey;
  String? statusKey;
  int? isCurrentlyStudying;
  String? createdAt;
  String? updatedAt;
  String? degree;
  String? location;
  String? country;

  UserProfileModelDataEducations({
    this.id,
    this.userId,
    this.schoolId,
    this.school,
    this.degreeKey,
    this.fieldOfStudy,
    this.studyPeriodFrom,
    this.studyPeriodTo,
    this.grade,
    this.description,
    this.locationKey,
    this.countryKey,
    this.statusKey,
    this.isCurrentlyStudying,
    this.createdAt,
    this.updatedAt,
    this.degree,
    this.location,
    this.country,
  });
  UserProfileModelDataEducations.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    userId = json["user_id"]?.toInt();
    schoolId = json["school_id"]?.toInt();
    school = json["school"]?.toString();
    degreeKey = json["degree_key"]?.toString();
    fieldOfStudy = json["field_of_study"]?.toString();
    studyPeriodFrom = json["study_period_from"]?.toString();
    studyPeriodTo = json["study_period_to"]?.toString();
    grade = json["grade"]?.toString();
    description = json["description"]?.toString();
    locationKey = json["location_key"]?.toString();
    countryKey = json["country_key"]?.toString();
    statusKey = json["status_key"]?.toString();
    isCurrentlyStudying = json["is_currently_studying"]?.toInt();
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    degree = json["degree"]?.toString();
    location = json["location"]?.toString();
    country = json["country"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["user_id"] = userId;
    data["school_id"] = schoolId;
    data["school"] = school;
    data["degree_key"] = degreeKey;
    data["field_of_study"] = fieldOfStudy;
    data["study_period_from"] = studyPeriodFrom;
    data["study_period_to"] = studyPeriodTo;
    data["grade"] = grade;
    data["description"] = description;
    data["location_key"] = locationKey;
    data["country_key"] = countryKey;
    data["status_key"] = statusKey;
    data["is_currently_studying"] = isCurrentlyStudying;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["degree"] = degree;
    data["location"] = location;
    data["country"] = country;
    return data;
  }
}

class UserProfileModelDataWorkXps {
/*
{
  "id": 2594042,
  "user_id": 2285293,
  "company_id": 20528,
  "company": "Just 4 Unique",
  "company_industry_key": "accounting_and_finance",
  "job_title_id": 269,
  "job_title": "R&D Engineer",
  "salary": 2323,
  "working_period_from": "2021-01-01",
  "working_period_to": "2021-02-01",
  "is_company_blacklisted": false,
  "is_currently_work_here": true,
  "description": "",
  "location_key": "albay",
  "country_key": "ph",
  "status_key": "active",
  "created_at": "2021-09-15T09:01:56.000000Z",
  "updated_at": "2021-09-15T09:04:43.000000Z",
  "company_logo": "https://assets.bossjob.com/companies/20528/logo/LsQR8uNoU1G9AqmMFdHAL3YY7lcuNXKhPpQXD1Se.png",
  "company_location": "Makati",
  "company_country": "Philippines",
  "location": "Albay",
  "country": "Philippines",
  "company_industry": "Accounting & Finance",
  "categories": {
    "52": "Actuarial/Statistics"
  }
} 
*/

  int? id;
  int? userId;
  int? companyId;
  String? company;
  String? companyIndustryKey;
  int? jobTitleId;
  String? jobTitle;
  int? salary;
  String? workingPeriodFrom;
  String? workingPeriodTo;
  bool? isCompanyBlacklisted;
  bool? isCurrentlyWorkHere;
  String? description;
  String? locationKey;
  String? countryKey;
  String? statusKey;
  String? createdAt;
  String? updatedAt;
  String? companyLogo;
  String? companyLocation;
  String? companyCountry;
  String? location;
  String? country;
  String? companyIndustry;
  XCATE? categories;

  UserProfileModelDataWorkXps({
    this.id,
    this.userId,
    this.companyId,
    this.company,
    this.companyIndustryKey,
    this.jobTitleId,
    this.jobTitle,
    this.salary,
    this.workingPeriodFrom,
    this.workingPeriodTo,
    this.isCompanyBlacklisted,
    this.isCurrentlyWorkHere,
    this.description,
    this.locationKey,
    this.countryKey,
    this.statusKey,
    this.createdAt,
    this.updatedAt,
    this.companyLogo,
    this.companyLocation,
    this.companyCountry,
    this.location,
    this.country,
    this.companyIndustry,
    this.categories,
  });
  UserProfileModelDataWorkXps.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    userId = json["user_id"]?.toInt();
    companyId = json["company_id"]?.toInt();
    company = json["company"]?.toString();
    companyIndustryKey = json["company_industry_key"]?.toString();
    jobTitleId = json["job_title_id"]?.toInt();
    jobTitle = json["job_title"]?.toString();
    salary = json["salary"]?.toInt();
    workingPeriodFrom = json["working_period_from"]?.toString();
    workingPeriodTo = json["working_period_to"]?.toString();
    isCompanyBlacklisted = json["is_company_blacklisted"];
    isCurrentlyWorkHere = json["is_currently_work_here"];
    description = json["description"]?.toString();
    locationKey = json["location_key"]?.toString();
    countryKey = json["country_key"]?.toString();
    statusKey = json["status_key"]?.toString();
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    companyLogo = json["company_logo"]?.toString();
    companyLocation = json["company_location"]?.toString();
    companyCountry = json["company_country"]?.toString();
    location = json["location"]?.toString();
    country = json["country"]?.toString();
    companyIndustry = json["company_industry"]?.toString();
    categories = (json["categories"] != null)
        ? XCATE.fromJson(json["categories"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["user_id"] = userId;
    data["company_id"] = companyId;
    data["company"] = company;
    data["company_industry_key"] = companyIndustryKey;
    data["job_title_id"] = jobTitleId;
    data["job_title"] = jobTitle;
    data["salary"] = salary;
    data["working_period_from"] = workingPeriodFrom;
    data["working_period_to"] = workingPeriodTo;
    data["is_company_blacklisted"] = isCompanyBlacklisted;
    data["is_currently_work_here"] = isCurrentlyWorkHere;
    data["description"] = description;
    data["location_key"] = locationKey;
    data["country_key"] = countryKey;
    data["status_key"] = statusKey;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["company_logo"] = companyLogo;
    data["company_location"] = companyLocation;
    data["company_country"] = companyCountry;
    data["location"] = location;
    data["country"] = country;
    data["company_industry"] = companyIndustry;
    if (categories != null) {
      data["categories"] = categories!.toJson();
    }
    return data;
  }
}

class UserProfileModelDataEmailSetting {
/*
{
  "system_email": true,
  "chat_email": true,
  "resume_email": true,
  "newsletter_email": true
} 
*/

  bool? systemEmail;
  bool? chatEmail;
  bool? resumeEmail;
  bool? newsletterEmail;

  UserProfileModelDataEmailSetting({
    this.systemEmail,
    this.chatEmail,
    this.resumeEmail,
    this.newsletterEmail,
  });
  UserProfileModelDataEmailSetting.fromJson(Map<String, dynamic> json) {
    systemEmail = json["system_email"];
    chatEmail = json["chat_email"];
    resumeEmail = json["resume_email"];
    newsletterEmail = json["newsletter_email"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["system_email"] = systemEmail;
    data["chat_email"] = chatEmail;
    data["resume_email"] = resumeEmail;
    data["newsletter_email"] = newsletterEmail;
    return data;
  }
}

class UserProfileModelDataProfile {
/*
{
  "percentage": 60,
  "incomplete": [
    "avatar"
  ]
} 
*/

  int? percentage;
  List<String?>? incomplete;

  UserProfileModelDataProfile({
    this.percentage,
    this.incomplete,
  });
  UserProfileModelDataProfile.fromJson(Map<String, dynamic> json) {
    percentage = json["percentage"]?.toInt();
    if (json["incomplete"] != null) {
      final v = json["incomplete"];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      incomplete = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["percentage"] = percentage;
    if (incomplete != null) {
      final v = incomplete;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data["incomplete"] = arr0;
    }
    return data;
  }
}

class UserProfileModelDataLatestResume {
/*
{
  "id": 3368906,
  "user_id": 2285293,
  "url": "https://assets.bossjob.com/users/2285293/resume/telegram_footer.png",
  "filename": "telegram_footer.png",
  "description": "",
  "is_active": 1,
  "status_key": "active",
  "is_parsed_es": 0,
  "created_at": "2021-09-10T07:59:39.000000Z",
  "updated_at": "2021-09-10T07:59:39.000000Z",
  "deleted_at": "",
  "is_uploaded_resume": 1
} 
*/

  int? id;
  int? userId;
  String? url;
  String? filename;
  String? description;
  int? isActive;
  String? statusKey;
  int? isParsedEs;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;
  int? isUploadedResume;

  UserProfileModelDataLatestResume({
    this.id,
    this.userId,
    this.url,
    this.filename,
    this.description,
    this.isActive,
    this.statusKey,
    this.isParsedEs,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.isUploadedResume,
  });
  UserProfileModelDataLatestResume.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    userId = json["user_id"]?.toInt();
    url = json["url"]?.toString();
    filename = json["filename"]?.toString();
    description = json["description"]?.toString();
    isActive = json["is_active"]?.toInt();
    statusKey = json["status_key"]?.toString();
    isParsedEs = json["is_parsed_es"]?.toInt();
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
    isUploadedResume = json["is_uploaded_resume"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["user_id"] = userId;
    data["url"] = url;
    data["filename"] = filename;
    data["description"] = description;
    data["is_active"] = isActive;
    data["status_key"] = statusKey;
    data["is_parsed_es"] = isParsedEs;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    data["is_uploaded_resume"] = isUploadedResume;
    return data;
  }
}

class UserProfileModelDataLatestPreferenceCategories {
/*
{
  "id": 57,
  "value": "Chemical Engineering"
} 
*/

  int? id;
  String? value;

  UserProfileModelDataLatestPreferenceCategories({
    this.id,
    this.value,
  });
  UserProfileModelDataLatestPreferenceCategories.fromJson(
      Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    value = json["value"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["value"] = value;
    return data;
  }
}

class UserProfileModelDataLatestPreference {
/*
{
  "id": 1490781,
  "user_id": 2285293,
  "job_title_id": "3",
  "job_title": "null",
  "location_key": "",
  "salary_range_from": 10000,
  "salary_range_to": 20000,
  "currency": "",
  "job_type_key": "",
  "industry_key": "",
  "country_key": "ph",
  "status_key": "active",
  "created_at": "2021-09-03T06:10:24.000000Z",
  "updated_at": "2021-09-14T02:59:27.000000Z",
  "location": "",
  "job_type": "",
  "country": "Philippines",
  "industry": "",
  "categories": [
    {
      "id": 57,
      "value": "Chemical Engineering"
    }
  ]
} 
*/

  int? id;
  int? userId;
  String? jobTitleId;
  String? jobTitle;
  String? locationKey;
  int? salaryRangeFrom;
  int? salaryRangeTo;
  String? currency;
  String? jobTypeKey;
  String? industryKey;
  String? countryKey;
  String? statusKey;
  String? createdAt;
  String? updatedAt;
  String? location;
  String? jobType;
  String? country;
  String? industry;
  List<UserProfileModelDataLatestPreferenceCategories?>? categories;

  UserProfileModelDataLatestPreference({
    this.id,
    this.userId,
    this.jobTitleId,
    this.jobTitle,
    this.locationKey,
    this.salaryRangeFrom,
    this.salaryRangeTo,
    this.currency,
    this.jobTypeKey,
    this.industryKey,
    this.countryKey,
    this.statusKey,
    this.createdAt,
    this.updatedAt,
    this.location,
    this.jobType,
    this.country,
    this.industry,
    this.categories,
  });
  UserProfileModelDataLatestPreference.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    userId = json["user_id"]?.toInt();
    jobTitleId = json["job_title_id"]?.toString();
    jobTitle = json["job_title"]?.toString();
    locationKey = json["location_key"]?.toString();
    salaryRangeFrom = json["salary_range_from"]?.toInt();
    salaryRangeTo = json["salary_range_to"]?.toInt();
    currency = json["currency"]?.toString();
    jobTypeKey = json["job_type_key"]?.toString();
    industryKey = json["industry_key"]?.toString();
    countryKey = json["country_key"]?.toString();
    statusKey = json["status_key"]?.toString();
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    location = json["location"]?.toString();
    jobType = json["job_type"]?.toString();
    country = json["country"]?.toString();
    industry = json["industry"]?.toString();
    if (json["categories"] != null) {
      final v = json["categories"];
      final arr0 = <UserProfileModelDataLatestPreferenceCategories>[];
      v.forEach((v) {
        arr0.add(UserProfileModelDataLatestPreferenceCategories.fromJson(v));
      });
      categories = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["user_id"] = userId;
    data["job_title_id"] = jobTitleId;
    data["job_title"] = jobTitle;
    data["location_key"] = locationKey;
    data["salary_range_from"] = salaryRangeFrom;
    data["salary_range_to"] = salaryRangeTo;
    data["currency"] = currency;
    data["job_type_key"] = jobTypeKey;
    data["industry_key"] = industryKey;
    data["country_key"] = countryKey;
    data["status_key"] = statusKey;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["location"] = location;
    data["job_type"] = jobType;
    data["country"] = country;
    data["industry"] = industry;
    if (categories != null) {
      final v = categories;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["categories"] = arr0;
    }
    return data;
  }
}

class XCATE {
  List<Map<String, String>>? categories = new List.empty(growable: true);

  XCATE(this.categories);
  XCATE.fromJson(Map<String, dynamic>? json) {
    if (json != null) {
      json.forEach((key, value) {
        categories!.add({key: value});
      });
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    categories!.forEach((element) {
      data.addEntries(element.entries);
    });
    return data;
  }
}

class UserProfileModelDataLatestWorkXp {
/*
{
  "id": 2594042,
  "user_id": 2285293,
  "company_id": 20528,
  "company": "Just 4 Unique",
  "company_industry_key": "accounting_and_finance",
  "job_title_id": 269,
  "job_title": "R&D Engineer",
  "salary": 2323,
  "working_period_from": "2021-01-01",
  "working_period_to": "2021-02-01",
  "is_company_blacklisted": false,
  "is_currently_work_here": true,
  "description": "",
  "location_key": "albay",
  "country_key": "ph",
  "status_key": "active",
  "created_at": "2021-09-15T09:01:56.000000Z",
  "updated_at": "2021-09-15T09:04:43.000000Z",
  "company_logo": "https://assets.bossjob.com/companies/20528/logo/LsQR8uNoU1G9AqmMFdHAL3YY7lcuNXKhPpQXD1Se.png",
  "company_location": "Makati",
  "company_country": "Philippines",
  "location": "Albay",
  "country": "Philippines",
  "company_industry": "Accounting & Finance",
  "categories": {
    "52": "Actuarial/Statistics"
  }
} 
*/

  int? id;
  int? userId;
  int? companyId;
  String? company;
  String? companyIndustryKey;
  int? jobTitleId;
  String? jobTitle;
  int? salary;
  String? workingPeriodFrom;
  String? workingPeriodTo;
  bool? isCompanyBlacklisted;
  bool? isCurrentlyWorkHere;
  String? description;
  String? locationKey;
  String? countryKey;
  String? statusKey;
  String? createdAt;
  String? updatedAt;
  String? companyLogo;
  String? companyLocation;
  String? companyCountry;
  String? location;
  String? country;
  String? companyIndustry;
  XCATE? categories;

  UserProfileModelDataLatestWorkXp({
    this.id,
    this.userId,
    this.companyId,
    this.company,
    this.companyIndustryKey,
    this.jobTitleId,
    this.jobTitle,
    this.salary,
    this.workingPeriodFrom,
    this.workingPeriodTo,
    this.isCompanyBlacklisted,
    this.isCurrentlyWorkHere,
    this.description,
    this.locationKey,
    this.countryKey,
    this.statusKey,
    this.createdAt,
    this.updatedAt,
    this.companyLogo,
    this.companyLocation,
    this.companyCountry,
    this.location,
    this.country,
    this.companyIndustry,
    this.categories,
  });
  UserProfileModelDataLatestWorkXp.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    userId = json["user_id"]?.toInt();
    companyId = json["company_id"]?.toInt();
    company = json["company"]?.toString();
    companyIndustryKey = json["company_industry_key"]?.toString();
    jobTitleId = json["job_title_id"]?.toInt();
    jobTitle = json["job_title"]?.toString();
    salary = json["salary"]?.toInt();
    workingPeriodFrom = json["working_period_from"]?.toString();
    workingPeriodTo = json["working_period_to"]?.toString();
    isCompanyBlacklisted = json["is_company_blacklisted"];
    isCurrentlyWorkHere = json["is_currently_work_here"];
    description = json["description"]?.toString();
    locationKey = json["location_key"]?.toString();
    countryKey = json["country_key"]?.toString();
    statusKey = json["status_key"]?.toString();
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    companyLogo = json["company_logo"]?.toString();
    companyLocation = json["company_location"]?.toString();
    companyCountry = json["company_country"]?.toString();
    location = json["location"]?.toString();
    country = json["country"]?.toString();
    companyIndustry = json["company_industry"]?.toString();
    categories = (json["categories"] != null)
        ? XCATE.fromJson(json["categories"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["user_id"] = userId;
    data["company_id"] = companyId;
    data["company"] = company;
    data["company_industry_key"] = companyIndustryKey;
    data["job_title_id"] = jobTitleId;
    data["job_title"] = jobTitle;
    data["salary"] = salary;
    data["working_period_from"] = workingPeriodFrom;
    data["working_period_to"] = workingPeriodTo;
    data["is_company_blacklisted"] = isCompanyBlacklisted;
    data["is_currently_work_here"] = isCurrentlyWorkHere;
    data["description"] = description;
    data["location_key"] = locationKey;
    data["country_key"] = countryKey;
    data["status_key"] = statusKey;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["company_logo"] = companyLogo;
    data["company_location"] = companyLocation;
    data["company_country"] = companyCountry;
    data["location"] = location;
    data["country"] = country;
    data["company_industry"] = companyIndustry;
    if (categories != null) {
      data["categories"] = categories!.toJson();
    }
    return data;
  }
}

class UserProfileModelDataLatestEducation {
/*
{
  "id": 2661629,
  "user_id": 2285293,
  "school_id": 167,
  "school": "Western Institute of Technology",
  "degree_key": "doctor",
  "field_of_study": "qwwqwqwwwww",
  "study_period_from": "2021-01-01",
  "study_period_to": "2021-03-01",
  "grade": "",
  "description": "",
  "location_key": "manila",
  "country_key": "ph",
  "status_key": "active",
  "is_currently_studying": 0,
  "created_at": "2021-09-03T06:11:11.000000Z",
  "updated_at": "2021-09-14T09:48:49.000000Z",
  "degree": "Doctor",
  "location": "Manila",
  "country": "Philippines"
} 
*/

  int? id;
  int? userId;
  int? schoolId;
  String? school;
  String? degreeKey;
  String? fieldOfStudy;
  String? studyPeriodFrom;
  String? studyPeriodTo;
  String? grade;
  String? description;
  String? locationKey;
  String? countryKey;
  String? statusKey;
  int? isCurrentlyStudying;
  String? createdAt;
  String? updatedAt;
  String? degree;
  String? location;
  String? country;

  UserProfileModelDataLatestEducation({
    this.id,
    this.userId,
    this.schoolId,
    this.school,
    this.degreeKey,
    this.fieldOfStudy,
    this.studyPeriodFrom,
    this.studyPeriodTo,
    this.grade,
    this.description,
    this.locationKey,
    this.countryKey,
    this.statusKey,
    this.isCurrentlyStudying,
    this.createdAt,
    this.updatedAt,
    this.degree,
    this.location,
    this.country,
  });
  UserProfileModelDataLatestEducation.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    userId = json["user_id"]?.toInt();
    schoolId = json["school_id"]?.toInt();
    school = json["school"]?.toString();
    degreeKey = json["degree_key"]?.toString();
    fieldOfStudy = json["field_of_study"]?.toString();
    studyPeriodFrom = json["study_period_from"]?.toString();
    studyPeriodTo = json["study_period_to"]?.toString();
    grade = json["grade"]?.toString();
    description = json["description"]?.toString();
    locationKey = json["location_key"]?.toString();
    countryKey = json["country_key"]?.toString();
    statusKey = json["status_key"]?.toString();
    isCurrentlyStudying = json["is_currently_studying"]?.toInt();
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    degree = json["degree"]?.toString();
    location = json["location"]?.toString();
    country = json["country"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["user_id"] = userId;
    data["school_id"] = schoolId;
    data["school"] = school;
    data["degree_key"] = degreeKey;
    data["field_of_study"] = fieldOfStudy;
    data["study_period_from"] = studyPeriodFrom;
    data["study_period_to"] = studyPeriodTo;
    data["grade"] = grade;
    data["description"] = description;
    data["location_key"] = locationKey;
    data["country_key"] = countryKey;
    data["status_key"] = statusKey;
    data["is_currently_studying"] = isCurrentlyStudying;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["degree"] = degree;
    data["location"] = location;
    data["country"] = country;
    return data;
  }
}

class UserProfileModelData {
/*
{
  "id": 2285293,
  "first_name": "sy",
  "last_name": "lim",
  "email": "syee@poseitech.com",
  "phone_num": "123123123",
  "gender": "",
  "age": "0",
  "birthdate": "",
  "address": "",
  "postal_code": "",
  "avatar": "",
  "country_key": "ph",
  "location_key": "alaminos",
  "website": "",
  "description": "",
  "xp_lvl_key": "",
  "employment_status_key": "",
  "fb_user_ref": "",
  "is_fb_messenger_active": 0,
  "is_email_verify": true,
  "is_mobile_verified": false,
  "is_subscribe": false,
  "is_job_salary_hidden": 0,
  "status_key": "active",
  "last_active_at": "2021-09-15 08:47:07",
  "notice_period_id": 3,
  "is_profile_completed": true,
  "job_post": 0,
  "credit": 0,
  "created_at": "2021-09-03T06:09:03.000000Z",
  "updated_at": "2021-09-15T00:47:07.000000Z",
  "active_key": 1,
  "is_visible": true,
  "masked_resume_url": "",
  "is_profile_update_required": false,
  "ats_user_id": 0,
  "no_show_num": 0,
  "xp_lvl": "",
  "latest_education": {
    "id": 2661629,
    "user_id": 2285293,
    "school_id": 167,
    "school": "Western Institute of Technology",
    "degree_key": "doctor",
    "field_of_study": "qwwqwqwwwww",
    "study_period_from": "2021-01-01",
    "study_period_to": "2021-03-01",
    "grade": "",
    "description": "",
    "location_key": "manila",
    "country_key": "ph",
    "status_key": "active",
    "is_currently_studying": 0,
    "created_at": "2021-09-03T06:11:11.000000Z",
    "updated_at": "2021-09-14T09:48:49.000000Z",
    "degree": "Doctor",
    "location": "Manila",
    "country": "Philippines"
  },
  "latest_work_xp": {
    "id": 2594042,
    "user_id": 2285293,
    "company_id": 20528,
    "company": "Just 4 Unique",
    "company_industry_key": "accounting_and_finance",
    "job_title_id": 269,
    "job_title": "R&D Engineer",
    "salary": 2323,
    "working_period_from": "2021-01-01",
    "working_period_to": "2021-02-01",
    "is_company_blacklisted": false,
    "is_currently_work_here": true,
    "description": "",
    "location_key": "albay",
    "country_key": "ph",
    "status_key": "active",
    "created_at": "2021-09-15T09:01:56.000000Z",
    "updated_at": "2021-09-15T09:04:43.000000Z",
    "company_logo": "https://assets.bossjob.com/companies/20528/logo/LsQR8uNoU1G9AqmMFdHAL3YY7lcuNXKhPpQXD1Se.png",
    "company_location": "Makati",
    "company_country": "Philippines",
    "location": "Albay",
    "country": "Philippines",
    "company_industry": "Accounting & Finance",
    "categories": {
      "52": "Actuarial/Statistics"
    }
  },
  "latest_preference": {
    "id": 1490781,
    "user_id": 2285293,
    "job_title_id": "3",
    "job_title": "null",
    "location_key": "",
    "salary_range_from": 10000,
    "salary_range_to": 20000,
    "currency": "",
    "job_type_key": "",
    "industry_key": "",
    "country_key": "ph",
    "status_key": "active",
    "created_at": "2021-09-03T06:10:24.000000Z",
    "updated_at": "2021-09-14T02:59:27.000000Z",
    "location": "",
    "job_type": "",
    "country": "Philippines",
    "industry": "",
    "categories": [
      {
        "id": 57,
        "value": "Chemical Engineering"
      }
    ]
  },
  "latest_resume": {
    "id": 3368906,
    "user_id": 2285293,
    "url": "https://assets.bossjob.com/users/2285293/resume/telegram_footer.png",
    "filename": "telegram_footer.png",
    "description": "",
    "is_active": 1,
    "status_key": "active",
    "is_parsed_es": 0,
    "created_at": "2021-09-10T07:59:39.000000Z",
    "updated_at": "2021-09-10T07:59:39.000000Z",
    "deleted_at": "",
    "is_uploaded_resume": 1
  },
  "country": "Philippines",
  "profile": {
    "percentage": 60,
    "incomplete": [
      "avatar"
    ]
  },
  "location": "Alaminos",
  "notice_period": "Two weeks",
  "social_links": "",
  "email_setting": {
    "system_email": true,
    "chat_email": true,
    "resume_email": true,
    "newsletter_email": true
  },
  "is_bosshunt_talent": true,
  "is_bosshunt_talent_active": true,
  "bosshunt_talent_opt_out_at": "2022-03-03 14:11:14",
  "work_xps": [
    {
      "id": 2594042,
      "user_id": 2285293,
      "company_id": 20528,
      "company": "Just 4 Unique",
      "company_industry_key": "accounting_and_finance",
      "job_title_id": 269,
      "job_title": "R&D Engineer",
      "salary": 2323,
      "working_period_from": "2021-01-01",
      "working_period_to": "2021-02-01",
      "is_company_blacklisted": false,
      "is_currently_work_here": true,
      "description": "",
      "location_key": "albay",
      "country_key": "ph",
      "status_key": "active",
      "created_at": "2021-09-15T09:01:56.000000Z",
      "updated_at": "2021-09-15T09:04:43.000000Z",
      "company_logo": "https://assets.bossjob.com/companies/20528/logo/LsQR8uNoU1G9AqmMFdHAL3YY7lcuNXKhPpQXD1Se.png",
      "company_location": "Makati",
      "company_country": "Philippines",
      "location": "Albay",
      "country": "Philippines",
      "company_industry": "Accounting & Finance",
      "categories": {
        "52": "Actuarial/Statistics"
      }
    }
  ],
  "educations": [
    {
      "id": 2661629,
      "user_id": 2285293,
      "school_id": 167,
      "school": "Western Institute of Technology",
      "degree_key": "doctor",
      "field_of_study": "qwwqwqwwwww",
      "study_period_from": "2021-01-01",
      "study_period_to": "2021-03-01",
      "grade": "",
      "description": "",
      "location_key": "manila",
      "country_key": "ph",
      "status_key": "active",
      "is_currently_studying": 0,
      "created_at": "2021-09-03T06:11:11.000000Z",
      "updated_at": "2021-09-14T09:48:49.000000Z",
      "degree": "Doctor",
      "location": "Manila",
      "country": "Philippines"
    }
  ],
  "skills": {
    "id": 406225,
    "user_id": 2285293,
    "job_skills": "",
    "created_at": "2021-09-10T01:53:33.000000Z",
    "updated_at": "2021-09-10T01:53:33.000000Z"
  }
} 
*/

  int? id;
  String? firstName;
  String? lastName;
  String? email;
  String? phoneNum;
  String? gender;
  String? age;
  String? birthdate;
  String? address;
  String? postalCode;
  String? avatar;
  String? countryKey;
  String? locationKey;
  String? website;
  String? description;
  String? xpLvlKey;
  String? employmentStatusKey;
  String? fbUserRef;
  int? isFbMessengerActive;
  bool? isEmailVerify;
  bool? isMobileVerified;
  bool? isSubscribe;
  int? isJobSalaryHidden;
  String? statusKey;
  String? lastActiveAt;
  int? noticePeriodId;
  bool? isProfileCompleted;
  int? jobPost;
  int? credit;
  String? createdAt;
  String? updatedAt;
  int? activeKey;
  bool? isVisible;
  String? maskedResumeUrl;
  bool? isProfileUpdateRequired;
  int? atsUserId;
  int? noShowNum;
  String? xpLvl;
  UserProfileModelDataLatestEducation? latestEducation;
  UserProfileModelDataLatestWorkXp? latestWorkXp;
  UserProfileModelDataLatestPreference? latestPreference;
  UserProfileModelDataLatestResume? latestResume;
  String? country;
  UserProfileModelDataProfile? profile;
  String? location;
  String? noticePeriod;
  String? socialLinks;
  UserProfileModelDataEmailSetting? emailSetting;
  bool? isBosshuntTalent;
  bool? isBosshuntTalentActive;
  String? bosshuntTalentOptOutAt;
  List<UserProfileModelDataWorkXps?>? workXps;
  List<UserProfileModelDataEducations?>? educations;
  UserProfileModelDataSkills? skills;

  UserProfileModelData({
    this.id,
    this.firstName,
    this.lastName,
    this.email,
    this.phoneNum,
    this.gender,
    this.age,
    this.birthdate,
    this.address,
    this.postalCode,
    this.avatar,
    this.countryKey,
    this.locationKey,
    this.website,
    this.description,
    this.xpLvlKey,
    this.employmentStatusKey,
    this.fbUserRef,
    this.isFbMessengerActive,
    this.isEmailVerify,
    this.isMobileVerified,
    this.isSubscribe,
    this.isJobSalaryHidden,
    this.statusKey,
    this.lastActiveAt,
    this.noticePeriodId,
    this.isProfileCompleted,
    this.jobPost,
    this.credit,
    this.createdAt,
    this.updatedAt,
    this.activeKey,
    this.isVisible,
    this.maskedResumeUrl,
    this.isProfileUpdateRequired,
    this.atsUserId,
    this.noShowNum,
    this.xpLvl,
    this.latestEducation,
    this.latestWorkXp,
    this.latestPreference,
    this.latestResume,
    this.country,
    this.profile,
    this.location,
    this.noticePeriod,
    this.socialLinks,
    this.emailSetting,
    this.isBosshuntTalent,
    this.isBosshuntTalentActive,
    this.bosshuntTalentOptOutAt,
    this.workXps,
    this.educations,
    this.skills,
  });
  UserProfileModelData.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    firstName = json["first_name"]?.toString();
    lastName = json["last_name"]?.toString();
    email = json["email"]?.toString();
    phoneNum = json["phone_num"]?.toString();
    gender = json["gender"]?.toString();
    age = json["age"]?.toString();
    birthdate = json["birthdate"]?.toString();
    address = json["address"]?.toString();
    postalCode = json["postal_code"]?.toString();
    avatar = json["avatar"]?.toString();
    countryKey = json["country_key"]?.toString();
    locationKey = json["location_key"]?.toString();
    website = json["website"]?.toString();
    description = json["description"]?.toString();
    xpLvlKey = json["xp_lvl_key"]?.toString();
    employmentStatusKey = json["employment_status_key"]?.toString();
    fbUserRef = json["fb_user_ref"]?.toString();
    isFbMessengerActive = json["is_fb_messenger_active"]?.toInt();
    isEmailVerify = json["is_email_verify"];
    isMobileVerified = json["is_mobile_verified"];
    isSubscribe = json["is_subscribe"];
    isJobSalaryHidden = json["is_job_salary_hidden"]?.toInt();
    statusKey = json["status_key"]?.toString();
    lastActiveAt = json["last_active_at"]?.toString();
    noticePeriodId = json["notice_period_id"]?.toInt();
    isProfileCompleted = json["is_profile_completed"];
    jobPost = json["job_post"]?.toInt();
    credit = json["credit"]?.toInt();
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    activeKey = json["active_key"]?.toInt();
    isVisible = json["is_visible"];
    maskedResumeUrl = json["masked_resume_url"]?.toString();
    isProfileUpdateRequired = json["is_profile_update_required"];
    atsUserId = json["ats_user_id"]?.toInt();
    noShowNum = json["no_show_num"]?.toInt();
    xpLvl = json["xp_lvl"]?.toString();
    latestEducation = (json["latest_education"] != null)
        ? UserProfileModelDataLatestEducation.fromJson(json["latest_education"])
        : null;
    latestWorkXp = (json["latest_work_xp"] != null)
        ? UserProfileModelDataLatestWorkXp.fromJson(json["latest_work_xp"])
        : null;
    latestPreference = (json["latest_preference"] != null)
        ? UserProfileModelDataLatestPreference.fromJson(
            json["latest_preference"])
        : null;
    latestResume = (json["latest_resume"] != null)
        ? UserProfileModelDataLatestResume.fromJson(json["latest_resume"])
        : null;
    country = json["country"]?.toString();
    profile = (json["profile"] != null)
        ? UserProfileModelDataProfile.fromJson(json["profile"])
        : null;
    location = json["location"]?.toString();
    noticePeriod = json["notice_period"]?.toString();
    socialLinks = json["social_links"]?.toString();
    emailSetting = (json["email_setting"] != null)
        ? UserProfileModelDataEmailSetting.fromJson(json["email_setting"])
        : null;
    isBosshuntTalent = json["is_bosshunt_talent"];
    isBosshuntTalentActive = json["is_bosshunt_talent_active"];
    bosshuntTalentOptOutAt = json["bosshunt_talent_opt_out_at"]?.toString();
    if (json["work_xps"] != null) {
      final v = json["work_xps"];
      final arr0 = <UserProfileModelDataWorkXps>[];
      v.forEach((v) {
        arr0.add(UserProfileModelDataWorkXps.fromJson(v));
      });
      workXps = arr0;
    }
    if (json["educations"] != null) {
      final v = json["educations"];
      final arr0 = <UserProfileModelDataEducations>[];
      v.forEach((v) {
        arr0.add(UserProfileModelDataEducations.fromJson(v));
      });
      educations = arr0;
    }
    skills = (json["skills"] != null)
        ? UserProfileModelDataSkills.fromJson(json["skills"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["first_name"] = firstName;
    data["last_name"] = lastName;
    data["email"] = email;
    data["phone_num"] = phoneNum;
    data["gender"] = gender;
    data["age"] = age;
    data["birthdate"] = birthdate;
    data["address"] = address;
    data["postal_code"] = postalCode;
    data["avatar"] = avatar;
    data["country_key"] = countryKey;
    data["location_key"] = locationKey;
    data["website"] = website;
    data["description"] = description;
    data["xp_lvl_key"] = xpLvlKey;
    data["employment_status_key"] = employmentStatusKey;
    data["fb_user_ref"] = fbUserRef;
    data["is_fb_messenger_active"] = isFbMessengerActive;
    data["is_email_verify"] = isEmailVerify;
    data["is_mobile_verified"] = isMobileVerified;
    data["is_subscribe"] = isSubscribe;
    data["is_job_salary_hidden"] = isJobSalaryHidden;
    data["status_key"] = statusKey;
    data["last_active_at"] = lastActiveAt;
    data["notice_period_id"] = noticePeriodId;
    data["is_profile_completed"] = isProfileCompleted;
    data["job_post"] = jobPost;
    data["credit"] = credit;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["active_key"] = activeKey;
    data["is_visible"] = isVisible;
    data["masked_resume_url"] = maskedResumeUrl;
    data["is_profile_update_required"] = isProfileUpdateRequired;
    data["ats_user_id"] = atsUserId;
    data["no_show_num"] = noShowNum;
    data["xp_lvl"] = xpLvl;
    if (latestEducation != null) {
      data["latest_education"] = latestEducation!.toJson();
    }
    if (latestWorkXp != null) {
      data["latest_work_xp"] = latestWorkXp!.toJson();
    }
    if (latestPreference != null) {
      data["latest_preference"] = latestPreference!.toJson();
    }
    if (latestResume != null) {
      data["latest_resume"] = latestResume!.toJson();
    }
    data["country"] = country;
    if (profile != null) {
      data["profile"] = profile!.toJson();
    }
    data["location"] = location;
    data["notice_period"] = noticePeriod;
    data["social_links"] = socialLinks;
    if (emailSetting != null) {
      data["email_setting"] = emailSetting!.toJson();
    }
    data["is_bosshunt_talent"] = isBosshuntTalent;
    data["is_bosshunt_talent_active"] = isBosshuntTalentActive;
    data["bosshunt_talent_opt_out_at"] = bosshuntTalentOptOutAt;
    if (workXps != null) {
      final v = workXps;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["work_xps"] = arr0;
    }
    if (educations != null) {
      final v = educations;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["educations"] = arr0;
    }
    if (skills != null) {
      data["skills"] = skills!.toJson();
    }
    return data;
  }
}

class UserProfileModel {
/*
{
  "message": "OK",
  "data": {
    "id": 2285293,
    "first_name": "sy",
    "last_name": "lim",
    "email": "syee@poseitech.com",
    "phone_num": "123123123",
    "gender": "",
    "age": "0",
    "birthdate": "",
    "address": "",
    "postal_code": "",
    "avatar": "",
    "country_key": "ph",
    "location_key": "alaminos",
    "website": "",
    "description": "",
    "xp_lvl_key": "",
    "employment_status_key": "",
    "fb_user_ref": "",
    "is_fb_messenger_active": 0,
    "is_email_verify": true,
    "is_mobile_verified": false,
    "is_subscribe": false,
    "is_job_salary_hidden": 0,
    "status_key": "active",
    "last_active_at": "2021-09-15 08:47:07",
    "notice_period_id": 3,
    "is_profile_completed": true,
    "job_post": 0,
    "credit": 0,
    "created_at": "2021-09-03T06:09:03.000000Z",
    "updated_at": "2021-09-15T00:47:07.000000Z",
    "active_key": 1,
    "is_visible": true,
    "masked_resume_url": "",
    "is_profile_update_required": false,
    "ats_user_id": 0,
    "no_show_num": 0,
    "xp_lvl": "",
    "latest_education": {
      "id": 2661629,
      "user_id": 2285293,
      "school_id": 167,
      "school": "Western Institute of Technology",
      "degree_key": "doctor",
      "field_of_study": "qwwqwqwwwww",
      "study_period_from": "2021-01-01",
      "study_period_to": "2021-03-01",
      "grade": "",
      "description": "",
      "location_key": "manila",
      "country_key": "ph",
      "status_key": "active",
      "is_currently_studying": 0,
      "created_at": "2021-09-03T06:11:11.000000Z",
      "updated_at": "2021-09-14T09:48:49.000000Z",
      "degree": "Doctor",
      "location": "Manila",
      "country": "Philippines"
    },
    "latest_work_xp": {
      "id": 2594042,
      "user_id": 2285293,
      "company_id": 20528,
      "company": "Just 4 Unique",
      "company_industry_key": "accounting_and_finance",
      "job_title_id": 269,
      "job_title": "R&D Engineer",
      "salary": 2323,
      "working_period_from": "2021-01-01",
      "working_period_to": "2021-02-01",
      "is_company_blacklisted": false,
      "is_currently_work_here": true,
      "description": "",
      "location_key": "albay",
      "country_key": "ph",
      "status_key": "active",
      "created_at": "2021-09-15T09:01:56.000000Z",
      "updated_at": "2021-09-15T09:04:43.000000Z",
      "company_logo": "https://assets.bossjob.com/companies/20528/logo/LsQR8uNoU1G9AqmMFdHAL3YY7lcuNXKhPpQXD1Se.png",
      "company_location": "Makati",
      "company_country": "Philippines",
      "location": "Albay",
      "country": "Philippines",
      "company_industry": "Accounting & Finance",
      "categories": {
        "52": "Actuarial/Statistics"
      }
    },
    "latest_preference": {
      "id": 1490781,
      "user_id": 2285293,
      "job_title_id": "3",
      "job_title": "null",
      "location_key": "",
      "salary_range_from": 10000,
      "salary_range_to": 20000,
      "currency": "",
      "job_type_key": "",
      "industry_key": "",
      "country_key": "ph",
      "status_key": "active",
      "created_at": "2021-09-03T06:10:24.000000Z",
      "updated_at": "2021-09-14T02:59:27.000000Z",
      "location": "",
      "job_type": "",
      "country": "Philippines",
      "industry": "",
      "categories": [
        {
          "id": 57,
          "value": "Chemical Engineering"
        }
      ]
    },
    "latest_resume": {
      "id": 3368906,
      "user_id": 2285293,
      "url": "https://assets.bossjob.com/users/2285293/resume/telegram_footer.png",
      "filename": "telegram_footer.png",
      "description": "",
      "is_active": 1,
      "status_key": "active",
      "is_parsed_es": 0,
      "created_at": "2021-09-10T07:59:39.000000Z",
      "updated_at": "2021-09-10T07:59:39.000000Z",
      "deleted_at": "",
      "is_uploaded_resume": 1
    },
    "country": "Philippines",
    "profile": {
      "percentage": 60,
      "incomplete": [
        "avatar"
      ]
    },
    "location": "Alaminos",
    "notice_period": "Two weeks",
    "social_links": "",
    "email_setting": {
      "system_email": true,
      "chat_email": true,
      "resume_email": true,
      "newsletter_email": true
    },
    "is_bosshunt_talent": true,
    "is_bosshunt_talent_active": true,
    "bosshunt_talent_opt_out_at": "2022-03-03 14:11:14",
    "work_xps": [
      {
        "id": 2594042,
        "user_id": 2285293,
        "company_id": 20528,
        "company": "Just 4 Unique",
        "company_industry_key": "accounting_and_finance",
        "job_title_id": 269,
        "job_title": "R&D Engineer",
        "salary": 2323,
        "working_period_from": "2021-01-01",
        "working_period_to": "2021-02-01",
        "is_company_blacklisted": false,
        "is_currently_work_here": true,
        "description": "",
        "location_key": "albay",
        "country_key": "ph",
        "status_key": "active",
        "created_at": "2021-09-15T09:01:56.000000Z",
        "updated_at": "2021-09-15T09:04:43.000000Z",
        "company_logo": "https://assets.bossjob.com/companies/20528/logo/LsQR8uNoU1G9AqmMFdHAL3YY7lcuNXKhPpQXD1Se.png",
        "company_location": "Makati",
        "company_country": "Philippines",
        "location": "Albay",
        "country": "Philippines",
        "company_industry": "Accounting & Finance",
        "categories": {
          "52": "Actuarial/Statistics"
        }
      }
    ],
    "educations": [
      {
        "id": 2661629,
        "user_id": 2285293,
        "school_id": 167,
        "school": "Western Institute of Technology",
        "degree_key": "doctor",
        "field_of_study": "qwwqwqwwwww",
        "study_period_from": "2021-01-01",
        "study_period_to": "2021-03-01",
        "grade": "",
        "description": "",
        "location_key": "manila",
        "country_key": "ph",
        "status_key": "active",
        "is_currently_studying": 0,
        "created_at": "2021-09-03T06:11:11.000000Z",
        "updated_at": "2021-09-14T09:48:49.000000Z",
        "degree": "Doctor",
        "location": "Manila",
        "country": "Philippines"
      }
    ],
    "skills": {
      "id": 406225,
      "user_id": 2285293,
      "job_skills": "",
      "created_at": "2021-09-10T01:53:33.000000Z",
      "updated_at": "2021-09-10T01:53:33.000000Z"
    }
  },
  "status_code": 200
} 
*/

  String? message;
  UserProfileModelData? data;
  int? statusCode;

  UserProfileModel({
    this.message,
    this.data,
    this.statusCode,
  });
  UserProfileModel.fromJson(Map<String, dynamic> json) {
    message = json["message"]?.toString();
    data = (json["data"] != null)
        ? UserProfileModelData.fromJson(json["data"])
        : null;
    statusCode = json["status_code"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["message"] = message;
    data["data"] = this.data!.toJson();
    data["status_code"] = statusCode;
    return data;
  }
}
